name: webapp
description: "Paltranco Web App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.5.0
  archive: ^4.0.9
  shared_preferences: ^2.5.3
  file_picker: ^10.3.2
  url_launcher: ^6.3.1
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  package_info_plus: ^8.3.1
  image: ^4.5.4
  xml: ^7.0.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/sdv_footer_lite.png
    - assets/export_templates/bs-regular.docx
    - assets/export_templates/bs-hustling.docx
    - assets/export_templates/bt-regular.docx
    - assets/export_templates/bt-hustling.docx
