const puertoPrincesaBarangayOptions = <String>[
  'Babuyan',
  'Bacungan',
  'Bagong Bayan',
  'Bagong Pag-asa',
  'Bagong Silang',
  'Bahile',
  'Bancao-Bancao',
  'Binduyan',
  'Buenavista',
  'Cabayugan',
  'Concepcion',
  'Irawan',
  'Inagawan',
  'Inagawan Sub-Colony',
  'Kamuning',
  'Langogan',
  'Liwanag',
  'Lucbuan',
  'Luzviminda',
  'Mabuhay',
  'Macarascas',
  'Magkakaibigan',
  'Mangingisda',
  'Manalo',
  'Mandaragat',
  'Marufinas',
  'Maunlad',
  'Milagrosa',
  'Model',
  'Montible',
  'Napsan',
  'New Panggangan',
  'Pagkakaisa',
  'Princesa',
  'Salvacion',
  'San Jose',
  'San Manuel',
  'San Miguel',
  'San Pedro',
  'San Rafael',
  'Santa Cruz',
  'Santa Lourdes',
  'Santa Lucia',
  'Santa Monica',
  'Sicsican',
  'Simpocan',
  'Tagabinet',
  'Tagburos',
  'Tagumpay',
  'Tanabag',
  'Tanglaw',
  'Tiniguiban',
];
